l_russian:
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Недостаточно Игроков"
 PRODUCTION_MATERIALS_COAL:0 "Уголь"
 PRODUCTION_MATERIALS_LAZURITE:0 "Лазурит"
 PRODUCTION_MATERIALS_REDSTONE:0 "Редстоун"
 PRODUCTION_MATERIALS_GUNPOWDER:0 "Порох"
 PRODUCTION_MATERIALS_WOOD:0 "Дерево"
 PRODUCTION_MATERIALS_IRON:0 "Железо"
 PRODUCTION_MATERIALS_DIAMONDS:0 "Алмазы"
 PRODUCTION_MATERIALS_NETHERITE:0 "Незерит"
 PRODUCTION_VEHICLES_BUTTON:0 "Построить Танки"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "Танки §RНе изобретенны§!!"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "Самолёты §RНе изобретенны§!!"
 PRODUCTION_CONSUMER_GOODS_DESC:1 "В условиях текущей экономической политики граждане ожидают, что $PERCENTAGE|H0%$ наших фабрик и военных заводов будут выпускать потребительские товары. Производители справляются с этим требованием, поэтому у нас есть до $OPERATIONAL|H$ фабрик, где для торговли можно использовать $TRADE_USABLE|H$."
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER:0 "Перенаправляются в §Yрезерв§! из-за нехватки §Hигроков§! для запрошенных §Yподкреплений§!"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Вместимость Самолёта/Авианосца"
 INTEL_ARMS_FACTORIES_USED_ON_ARMOR:0 "Военные заводы, используемые на танки"
 INTEL_ARMS_FACTORIES_USED_ON_AIR:0 "Военные заводы, используемые на самолёты"
